apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: community-voting-service
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: community-voting-service}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: ingress-nginx}
      ports: [{protocol: TCP, port: 8080}]
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
        - {protocol: TCP, port: 5432}

