apiVersion: v1
kind: Service
metadata:
  name: community-voting-service
spec:
  selector: {app.kubernetes.io/name: community-voting-service}
  ports: [{name: http, port: {{ .Values.service.port }}, targetPort: http}]

